random_seed: 42
models:
  clip:
    batch_size: 16
  siglip2:
    batch_size: 16
  dinov2:
    batch_size: 16
data_cache: "./data"
datasets:
  tid2013:
    clean: false
    urls:
      tid2013: "https://www.ponomarenko.info/tid2013/tid2013.rar"
embeddings:
  out: "./data/embeddings"
weights_out: "./out/weights"